'use strict';
// Static native source checks only. No Delphi compiler or Android UI is executed.
require('./verify_fix19_ui');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const apk=path.join(__dirname,'ApkWinSock_Android64'),read=n=>fs.readFileSync(path.join(apk,n),'utf8');
const methods=read('ApkWinSock.Methods.inc'),fields=read('ApkWinSock.Fields.inc');
const files=fs.readdirSync(apk).filter(n=>/^ApkWinSock\..+\.inc$/.test(n)),all=files.map(read).join('\n');
const declared=[...fields.matchAll(/^\s*(F\w+)\s*:/gm)].map(m=>m[1]);
assert.equal(new Set(declared).size,declared.length,'Duplicate form field');
for(const m of all.matchAll(/\b(FSupport\w+)\b/g))assert.ok(declared.includes(m[1]),'Missing field '+m[1]);
const supportNames=[];
const parameters=x=>(x||'').replace(/\s*=\s*[^;]+/g,'').split(';').flatMap(p=>{const [names,type]=p.trim().split(':');return type?names.replace(/^(const|var|out)\s+/,'').split(',').map(n=>n.trim()+':'+type.trim()):[]});
for(const m of all.matchAll(/\b(procedure|function) TForm1\.(\w*Support\w*)\s*(?:\(([^)]*)\))?\s*(?::\s*(\w+))?\s*;/g)){
 const d=methods.match(new RegExp('\\b'+m[1]+' '+m[2]+'\\s*(?:\\(([^)]*)\\))?\\s*(?::\\s*(\\w+))?\\s*;'));
 assert.ok(d,'Missing support declaration '+m[2]);assert.deepEqual(parameters(m[3]),parameters(d[1]),'Signature '+m[2]);assert.equal(m[4],d[2]);supportNames.push(m[2]);
}
assert.equal(new Set(supportNames).size,supportNames.length,'Duplicate support method');
for(const m of methods.matchAll(/\b(?:procedure|function) (\w*Support\w*)\b/g))assert.ok(supportNames.includes(m[1]),'Missing implementation '+m[1]);
for(const part of ['Ui','Help','Messages','Flow','Permissions','Protocol'])assert.ok(read('ApkWinSock.Support.inc').includes('{$I ApkWinSock.Support.'+part+'.inc}'));
for(const m of all.matchAll(/\{\$I\s+([^}]+)\}/g))assert.ok(fs.existsSync(path.join(apk,m[1].trim())),m[1]);
const me=read('ApkWinSock.Member.MyPage.inc').split('procedure TForm1.HubRenderMe')[1].split('procedure TForm1.HubRenderHistory')[0];
for(const action of ['orders','payments','myfeed','support'])assert.ok(!me.includes("'"+action+"'"),'Removed profile shortcut '+action);
for(const marker of ["HubProfileStat(C,'게시물'","HubProfileStat(C,'팔로워'","HubProfileStat(C,'팔로잉'","HubObject(Data,'posts')"])assert.ok(me.includes(marker),marker);
const grid=read('ApkWinSock.Member.MyPage.inc').split('procedure TForm1.HubRenderPostGrid')[1].split('procedure TForm1.HubRenderMe')[0];
assert.ok(grid.includes("'comments|'"));assert.ok(grid.includes('C.ClipChildren:=True'));
assert.ok(!me.includes("'QR 충전'")&&!me.includes("'charge'"));
const news=read('ApkWinSock.Member.NewsShop.inc'),lists=news.split('procedure TForm1.HubRenderArticle')[0];
assert.ok(!lists.includes("'body'")&&!lists.includes("'description'"),'List must not repeat full details');
assert.ok(news.includes('HubNewsBadge'));assert.ok(!lists.includes('HubDate('),'Dates are detail-only');
for(const marker of ['Periods:array[0..3] of Integer=(1,7,15,30)','TDropDownKind.Custom',"ListBoxResource:='listboxstyle'",'ListBox.OnApplyStyleLookup:=HubPlanPopupStyle','ListItems[I].StyledSettings:=[]'])assert.ok(news.includes(marker),marker);
const motion=read('ApkWinSock.Member.Motion.inc');assert.ok(!motion.includes('TControl(Background).Opacity:=0'),'Never hide input/popup containers with text children');
assert.ok(motion.includes('TControl(Background).Visible:=True'));
const menu=read('ApkWinSock.Member.Menu.inc');assert.ok(menu.includes("'search',14,13,22,22"));assert.ok(menu.includes('FHubSearchPrompt.SetBounds(48,2,C.Width-60,44)'));
assert.ok(menu.includes('FHubSearchPrompt.HitTest:=False'));assert.ok(menu.includes('OnChangeTracking:=HubMenuSearchChanged'));assert.ok(!menu.includes('menu.category'));
const feed=read('ApkWinSock.Member.Feed.inc'),timeline=feed.split('procedure TForm1.HubRenderFeed')[1].split('procedure TForm1.HubRenderComments')[0];
assert.ok(!timeline.includes('HubCard(')&&!timeline.includes('compose')&&!timeline.includes('HubButton('));
assert.ok(feed.includes('L.SetBounds(48,32,Header.Width-54,22)'));assert.ok(feed.includes("'팔로워 '"));assert.ok(feed.includes("' · 팔로잉 '"));
const dashboard=read('ApkWinSock.Dashboard.inc');assert.ok(dashboard.includes('FHubHeaderAction.SetBounds(W-52,4,48,48)'));assert.ok(dashboard.includes("FHubHeaderAction.TagString:='compose'"));
assert.ok(dashboard.includes("MemberSvg('create')"));assert.ok(dashboard.includes("MemberSvg('hamburger')"));
const theme=read('ApkMemberTheme.pas');
const body=name=>theme.split('function '+name+':TAlphaColor;').at(-1).split('end;')[0];
assert.equal(body('MemberBackground'),body('MemberSurface'));assert.ok(body('MemberBackground').includes('$FF000000'));assert.ok(body('MemberBackground').includes('$FFFFFFFF'));
assert.ok(read('ApkSystemBars.pas').includes('-16777216'));assert.ok(dashboard.includes('SupportApplyTheme'));
const ui=read('ApkWinSock.Support.Ui.inc'),flow=read('ApkWinSock.Support.Flow.inc'),help=read('ApkWinSock.Support.Help.inc'),messages=read('ApkWinSock.Support.Messages.inc'),protocol=read('ApkWinSock.Support.Protocol.inc');
const open=flow.split('procedure TForm1.SupportClick')[1].split('procedure TForm1.SupportStartBot')[0];
assert.ok(open.includes("FSupportView:='home'"));assert.ok(!open.includes('SUPPORT_BOT_OPEN')&&!open.includes('SupportStartBot'));
assert.ok(ui.includes('FSupportCard.Align:=TAlignLayout.Client'));assert.ok(ui.includes('FSupportTouch.BindScroll(FSupportTranscript)'));
assert.ok(ui.includes('OnChangeTracking:=SupportInputChanged'));assert.ok(ui.includes('FSupportBotReady'));
assert.ok(!all.includes('FSupportMemo'));assert.ok(messages.includes("Role='BOT'"));assert.ok(messages.includes('FSupportTouch.Busy'));
assert.ok(messages.includes('FSupportMessages.Count-FSupportVisibleMessages'));assert.ok(help.includes('Inc(FSupportVisibleMessages,100)'));
assert.ok(flow.includes("'SUPPORT_HELP|'"));assert.ok(flow.includes("'SUPPORT_BOT_OPEN|'"));assert.ok(help.includes("FSupportInput.Text:='상담원 연결'"));
assert.ok(protocol.includes("(Role <> 'BOT')"));assert.ok(protocol.includes('Seq > FSupportLastSeq + 1'));assert.ok(protocol.includes('Epoch <> FSupportEpoch'));
assert.ok(protocol.includes('FSupportMessages.Clear'));assert.ok(protocol.includes('MessageID = FSupportPendingID'));
assert.ok(read('ApkWinSock.Service.inc').includes('FSupportMessages.Clear;FreeAndNil(FSupportHelp)'));assert.ok(read('ApkWinSock.Lifecycle.Construction.inc').includes('FreeAndNil(FSupportHelp);FreeAndNil(FSupportMessages)'));
assert.ok(dashboard.indexOf('SupportCloseClick(nil)')<dashboard.indexOf('if FClosing or not Assigned(FFinalPanel) or not FFinalPanel.Visible then Exit;'));
console.log('FIX20 UI SOURCE PASS: native declarations/includes, profile statistics/text grid, header compose, separated list/detail, visible styled periods, centered search, uniform themes, FAQ-first support, bubble rendering, scroll guards, cursor/retry and cleanup');
