'use strict';
// Native source/lifetime checks, not a Delphi compiler or a device UI test.
require('./verify_fix20_ui');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const apk=path.join(__dirname,'ApkWinSock_Android64'),read=n=>fs.readFileSync(path.join(apk,n),'utf8');
const dashboard=read('ApkWinSock.Dashboard.inc'),flow=read('ApkWinSock.Member.Flow.inc'),actions=read('ApkWinSock.Member.Actions.inc');
assert.ok(dashboard.includes("0: Result:='menu'; 1: Result:='news'; 2: Result:='catalog'; 3: Result:='feed'; else Result:='me'"));
assert.ok(read('ApkWinSock.Service.inc').includes("FHubView := 'menu'"));
assert.ok(dashboard.includes("['home','news','shop','feed','user']"));
assert.ok(!dashboard.includes("FHubHeaderMenuIcon.Visible"));assert.ok(dashboard.includes("FHubHeaderAction.TagString:='all'"));
assert.ok(dashboard.includes('(I<>4) and (I=FDashboardActiveTab)'));assert.ok(dashboard.includes('FHubTabAvatar:=TCircle.Create(Self)'));
const media=read('ApkWinSock.Member.Media.inc');assert.ok(media.includes('FHubTabAvatar.Fill.Bitmap.Bitmap.LoadFromStream'));assert.ok(media.includes('FHubOwnPhotoKey<>Key'));
assert.ok(media.includes("HubNumber(Profile,'profileRevision')<HubNumber(FHubOwnProfile,'profileRevision')"));
assert.ok(read('ApkWinSock.Lifecycle.Construction.inc').includes('FreeAndNil(FHubOwnProfile)'));assert.ok(read('ApkWinSock.Service.inc').includes("FreeAndNil(FHubOwnProfile);FHubOwnPhotoKey:=''"));
assert.ok(flow.includes("HubRememberViewer(HubObject(Data,'viewer'))"));assert.ok(flow.includes("Action='member'"));assert.ok(flow.includes("Body.AddPair('id',FHubPostID)"));
assert.ok(actions.includes("HubNavigate('member','',ID)"));assert.ok(actions.includes("HubNavigate('follows',ID,ReturnView)"));
const my=read('ApkWinSock.Member.MyPage.inc'),me=my.split('procedure TForm1.HubRenderMe')[1].split('procedure TForm1.HubRenderMember')[0];
assert.ok(!me.includes("'balance'")&&!me.includes("'charge'"));assert.ok(me.includes("'@'+HubText(Profile,'handle'"));
assert.ok(my.includes('20+(I mod 3)*(CellW+10)'));assert.ok(my.includes("'follows|followers|'+ID"));assert.ok(my.includes("'follows|following|'+ID"));
const menu=read('ApkWinSock.Member.Menu.inc');assert.ok(!menu.includes('Details:='));assert.ok(menu.includes('L.SetBounds(51,0,C.Width-82,62)'));assert.ok(menu.includes('TApkMemberEdit.Create'));
const input=read('ApkMemberInput.pas');
const declarations=[...input.split('implementation')[0].matchAll(/\b(?:constructor|procedure|function)\s+(\w+)/g)].map(m=>m[1]).sort();
const implementations=[...input.matchAll(/\b(?:constructor|procedure|function)\s+TApkMember(?:Edit|Combo)\.(\w+)/g)].map(m=>m[1]).sort();assert.deepEqual(declarations,implementations);
for(const marker of ['function GetStyleObject: TFmxObject; override','TControlType.Styled',"Content.StyleName:='content'","AddBrush('foreground',MemberText)","AddBrush('selection',$55888888)"])assert.ok(input.includes(marker),marker);
assert.ok(!input.includes('TBitmap')&&!input.includes('TActiveStyleObject'),'Input background does not inherit a platform bitmap');
assert.ok(read('ApkWinSock.Support.Ui.inc').includes('FSupportInput:=TApkMemberEdit.Create(Self)'));
const widgets=read('ApkWinSock.Member.Widgets.inc');assert.ok(widgets.includes('Layout.TextHeight'));assert.ok(widgets.includes('Layout.TextWidth'));assert.ok(widgets.includes("Flat:=False"));
assert.ok(read('ApkWinSock.Support.Messages.inc').includes('SupportBubbleSize(Value,Text.TextSettings.Font'));assert.ok(!read('ApkWinSock.Support.Messages.inc').includes('Length(Value)*7'));
const motion=read('ApkWinSock.Member.Motion.inc'),feed=read('ApkWinSock.Member.Feed.inc');
assert.ok(motion.includes('IconBox.ClipChildren:=True'));assert.ok(motion.includes('IconBox,Icon,0,0,22,22'));
assert.ok(read('ApkWinSock.Member.Purchase.inc').includes('Item.AddPair(Name,TJSONObject.ParseJSONValue(Value.ToJSON))'));assert.ok(feed.includes("'member|'+AuthorID"));assert.ok(read('ApkWinSock.Member.Social.inc').includes("'social.report'"));
assert.ok(feed.includes('10+W,Y,W,44'));assert.ok(feed.includes('HubTextWidth(HubText(Author'));
const news=read('ApkWinSock.Member.NewsShop.inc'),lists=news.split('procedure TForm1.HubRenderArticle')[0];
assert.ok(news.includes('HubNewsBadge'));assert.ok(lists.includes('열람하려면 게시글을 눌러주세요.'));assert.ok(!lists.includes('HubDate('));
assert.ok(news.includes("HubNumber(FHubSelected,'views')"));assert.ok(news.includes("HubText(FHubSelected,'image')"));assert.ok(flow.includes("Body.AddPair('summary',TJSONBool.Create(True))"));
for(const key of ['releaseDate','developer','publisher','genre','ageRating','language','platform'])assert.ok(news.includes("'"+key+"'"),key);
assert.ok(!news.includes('HubGameSpecs'));assert.ok(!actions.includes("if Action='spec'"));assert.ok(actions.includes('AndroidOpenWebLink(ID)'));
const loading=read('ApkWinSock.Member.Loading.inc');assert.ok(!flow.includes('잠시만 기다려주세요'));assert.ok(loading.includes('FHubSkeleton and FFinalPanel.Visible'));
assert.ok(loading.includes('FHubBusyVeil.HitTest')===false);assert.ok(dashboard.includes('FHubBusyVeil.HitTest:=False'));assert.ok(loading.includes('not FForeground'));
assert.ok(read('ApkWinSock.Service.inc').includes('FHubBusyTimer.Enabled:=False'));
const refresh=read('ApkWinSock.Member.Refresh.inc');assert.ok(!refresh.includes('FHubRefreshLabel'));assert.ok(refresh.includes('FHubRefreshBadge.Fill.Kind:=TBrushKind.None'));assert.ok(read('ApkMemberRefresh.pas').includes('FTimer.Interval:=16'));
const qr=read('ApkQrRenderer.pas');assert.ok(qr.includes('Image.Bitmap.Clear(MemberBackground)'));assert.ok(qr.includes('Image.Bitmap.Canvas.Fill.Color := MemberText'));assert.ok(qr.includes('QUIET_ZONE_MODULES = 8'));
assert.ok(read('ApkWinSock.QrAuth.inc').includes('FQrInstructionText.TextSettings.FontColor:=MemberMuted'));
console.log('FIX21 UI SOURCE PASS: five-tab routing, avatar refresh/cleanup, local All/Settings, public profile and follow links, custom edit style, measured bubbles, isolated reaction bounds, rounded cards, article photos/views, game metadata/specs, placeholder-free loading and themed QR');
