'use strict';

const config = require('../config/config');

module.exports = {
    serviceEnabled: true,
    maintenanceMode: false,
    minProtocolVersion: config.DEFAULT_MIN_PROTOCOL_VERSION,
    minServerVersion: config.DEFAULT_MIN_SERVER_VERSION,
    minClientVersion: config.DEFAULT_MIN_CLIENT_VERSION,
    maintenanceSchedule: null,

    servers: new Map(),
    clients: new Map(),
    serverIdentities: new Map(),
    clientIdentities: new Map(),
    licenses: new Map(),

    disabledServers: new Set(),
    drainingServers: new Set(),
    disabledClients: new Set(),
    kickedServers: new Map(),
    kickedClients: new Map(),

    requestHistory: new Map(),
    requestTraces: new Map(),
    pendingRequests: new Map(),
    rateLimits: new Map(),
    events: [],
    notifications: [],
    nextNotificationId: 1,

    confirmTokens: new Map(),
    ipHistory: new Map(),
    serverAliases: new Map(),
    clientAliases: new Map(),
    serverNotes: new Map(),
    clientNotes: new Map(),
    serverDrainMeta: new Map(),

    desiredRuntimeConfig: {
        revision: 1,
        reconnectBaseMs: 500,
        reconnectMaxMs: 30000,
        reconnectJitterPct: 25,
        heartbeatMs: 10000,
        featureFlags: {}
    },
    serverFeatureOverrides: new Map(),
    clientFeatureOverrides: new Map(),
    serverProtocolProfiles: new Map(),
    clientProtocolProfiles: new Map(),
    deviceSecrets: new Map(),
    deviceAuthStatus: new Map(),
    deviceAuthChallenges: new Map(),
    deviceInfo: new Map(),
    deviceCapabilities: new Map(),
    deviceDiagnostics: new Map(),
    clientUiStates: new Map(),
    releaseCatalog: new Map(),
    deviceReleaseChannels: new Map(),
    deviceUpdateStatus: new Map(),
    configHistory: [],
    enrollmentPolicy: { enabled: false, updatedAt: 0 },
    deviceEnrollments: new Map(),
    deviceSecretRotations: new Map(),
    deviceSecretMeta: new Map(),
    deviceNetworkProfiles: new Map(),
    emergencyFailoverPolicy: { enabled: false, autoReturn: true, offlineGraceSeconds: 15, returnGraceSeconds: 30, maxMovesPerCycle: 50, updatedAt: 0 },
    clientFailoverEnabled: new Set(),
    clientFailoverRecords: new Map(),
    clientServerBindings: new Map(),
    offlineQueuePolicy: {
        enabled: false,
        maxItemsPerClient: 100,
        ttlSeconds: 3600,
        maxDeliveryAttempts: 5,
        updatedAt: 0
    },
    clientOfflineQueueEnabled: new Set(),
    offlineQueue: new Map(),
    deadLetters: new Map(),
    numberProcessingPolicy: {
        revision: 1,
        enabled: true,
        processor: 'DEFAULT',
        minValue: '',
        maxValue: '',
        blockedValues: [],
        updatedAt: 0
    },
    processorStats: new Map(),
    pushSubscriptions: new Map(),
    dailyHealthReports: new Map(),
    dailyHealthAccumulator: null,
    pendingDeviceCommands: new Map(),
    licenseRevision: 0,
    qrAuthRequests: new Map(),
    clientPasswordProfiles: new Map(),
    clientPasswordChallenges: new Map(),
    pendingBuildGrants: new Map(),
    buildSessions: new Map(),
    clientBuildBindings: new Map(),
    buildSessionPolicy: {
        ttlMinutes: config.DEFAULT_BUILD_SESSION_TTL_MINUTES,
        updatedAt: 0,
        updatedBy: 'DEFAULT'
    },

    runtimeStats: {
        startedAt: Date.now(),
        totalConnections: 0,
        serverReconnects: new Map(),
        clientReconnects: new Map(),
        ackOk: 0,
        ackError: 0,
        ackTimeout: 0,
        ackRetries: 0,
        queuedRequests: 0,
        dequeuedRequests: 0,
        replayedRequests: 0,
        deadLetteredRequests: 0,
        notices: 0,
        serverAckStats: new Map(),
        clientAckStats: new Map(),
        serverReconnectHistory: new Map(),
        clientReconnectHistory: new Map(),
        serverFlappingAlerts: new Map(),
        clientFlappingAlerts: new Map(),
        lastDatabaseSaveAt: 0,
        lastDatabaseSaveOk: true,
        lastDatabaseSize: 0,
        lastBackupAt: 0,
        lastBackupFile: ''
    }
};
